#!/bin/sh
# Simple init script for rpi_web_app

DAEMON=/usr/bin/rpi_web_app
PIDFILE=/var/run/rpi_web_app.pid

case "$1" in
  start)
    echo "Starting rpi_web_app..."
    start-stop-daemon -S -b -m -p "$PIDFILE" --exec "$DAEMON"
    ;;
  stop)
    echo "Stopping rpi_web_app..."
    start-stop-daemon -K -p "$PIDFILE"
    rm -f "$PIDFILE"
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
