#!/bin/sh

set -e

case "$1" in
    start)
        echo "Starting rpi_sensors"
        start-stop-daemon -S -n rpi_sensors -a /usr/bin/rpi_sensors -- -d
        ;;
    stop)
        echo "Stopping rpi_sensors"
        start-stop-daemon -K -n rpi_sensors
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
